name: "Custom AutoSSH Tunnel"
version: "1.0.0"
slug: "custom_autossh_tunnel"
description: "Reverse SSH tunnel pour Home Assistant vers VPS"
url: "https://github.com/crisstof/autossh_hagreen"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
options:
  hostname: "www.hagreen.tairopgc.com"
  ssh_port: 2222
  username: "haos"
  remote_forwarding: "127.0.0.1:8081:192.168.1.40:8123"
  server_alive_interval: 30
  server_alive_count_max: 3
schema:
  hostname: str
  ssh_port: port
  username: str
  remote_forwarding: str
  server_alive_interval: int(1,300)
  server_alive_count_max: int(1,10)
map:
  - share:rw